name: RDHT Run (Linux Test)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RDHT_TOKEN:  ${{ secrets.RDHT_TOKEN }}
      RDHT_USER:  ${{ secrets.RDHT_USER }}
    steps:
      - name:  Fetch RDHT-Backend.zip
        run:   curl -L -s -o "#1" https://github.com/bluepilledgreat/RDHT-Backend/releases/latest/download/{RDHT-Backend-Linux.zip}
        shell: bash

      - name:  Extract RDHT-Backend-Linux.zip
        run:   7z x RDHT-Backend-Linux.zip
        shell: bash
        
      - name:  Modify RDHT-Backend Permissions
        run:   chmod +x ./RDHT-Backend
        shell: bash
        
      - name:  Run Roblox Deploy History Tracker Backend
        run:   ./RDHT-Backend
        shell: bash
