name: RDHT Run

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RDHT_TOKEN:  ${{ secrets.RDHT_TOKEN }}
      RDHT_USER:  ${{ secrets.RDHT_USER }}
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name:  Fetch RDHT-Backend-Linux.zip
        run:   curl -L -s -o "#1" https://github.com/RobloxExploitingUnion/RDHT-Backend/releases/latest/download/{RDHT-Backend-Linux.zip}
        shell: bash

      - name:  Extract RDHT-Backend-Linux.zip
        run:   7z x RDHT-Backend-Linux.zip
        shell: bash
        
      - name:  Modify RDHT-Backend Permissions
        run:   chmod +x ./RDHT-Backend
        shell: bash
        
      - name:  Run Roblox Deploy History Tracker Backend
        run:   ./RDHT-Backend
        shell: bash
